// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://foqayctyxrpjgsnkyhna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZvcWF5Y3R5eHJwamdzbmt5aG5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMzg4NzUsImV4cCI6MjA3NDcxNDg3NX0.bPeZb-2Kvzw96c9NeEEbojBs_WQn5RWUk3tvA5C2JiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});